import React, { useState } from 'react';
import ResultDisplay from '../components/ResultDisplay';
import Loader from '../components/Loader';
import { detectText } from '../services/api';
import './DetectionPage.css';

const SAMPLE_TEXTS = {
  human: `I was sitting at my kitchen table last Tuesday when I realized I'd completely forgotten about my cousin's birthday. The panic set in immediately. I scrambled to call my mom, who, as usual, somehow already knew and had picked up a card on my behalf. I honestly don't know how she does it every single year.`,
  ai: `The proliferation of artificial intelligence technologies has fundamentally transformed the contemporary landscape of human-computer interaction. Natural language processing systems, leveraging transformer architectures trained on extensive corpora, demonstrate remarkable capabilities in generating contextually appropriate textual responses across diverse domains and applications.`
};

export default function TextPage() {
  const [text, setText] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  async function handleSubmit() {
    if (!text.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const data = await detectText(text);
      setResult(data);
    } catch (err) {
      setError(err.response?.data?.error || err.message || 'Detection failed');
    } finally {
      setLoading(false);
    }
  }

  function handleReset() {
    setText('');
    setResult(null);
    setError(null);
  }

  return (
    <div className="page-wrapper">
      <div className="page-header">
        <h1>📝 AI Text Detection</h1>
        <p>Paste text to detect if it was written by a human or generated by AI</p>
      </div>

      <div className="card">
        <div className="sample-buttons">
          <span className="sample-label">Try samples:</span>
          <button className="btn btn-secondary small" onClick={() => { setText(SAMPLE_TEXTS.human); setResult(null); }}>
            Human text
          </button>
          <button className="btn btn-secondary small" onClick={() => { setText(SAMPLE_TEXTS.ai); setResult(null); }}>
            AI text
          </button>
        </div>

        <textarea
          className="text-input"
          value={text}
          onChange={e => { setText(e.target.value); setResult(null); }}
          placeholder="Paste your text here (minimum 20 characters)..."
          rows={8}
        />

        <div className="text-stats">
          <span>{text.length} / 10000 chars</span>
          <span>{text.trim().split(/\s+/).filter(Boolean).length} words</span>
        </div>

        {error && <div className="error-banner">{error}</div>}

        <div className="action-row">
          <button
            className="btn btn-primary"
            onClick={handleSubmit}
            disabled={text.trim().length < 20 || loading}
          >
            {loading ? 'Analyzing...' : '🔍 Detect AI Text'}
          </button>
          {(text || result) && (
            <button className="btn btn-secondary" onClick={handleReset}>↩ Reset</button>
          )}
        </div>
      </div>

      {loading && <Loader message="Analyzing linguistic patterns..." />}
      {result && <ResultDisplay result={result} modality="text" />}
    </div>
  );
}
