"""
AI-Generated Text Detection Model
TF-IDF + Multinomial Naive Bayes pipeline
"""

import re
import logging
import joblib
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.calibration import CalibratedClassifierCV
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

logger = logging.getLogger(__name__)

# Download required NLTK data (run once)
def download_nltk_data():
    """Ensure required NLTK datasets are downloaded"""
    resources = ['stopwords', 'wordnet', 'punkt', 'averaged_perceptron_tagger']
    for resource in resources:
        try:
            nltk.data.find(f'corpora/{resource}')
        except LookupError:
            try:
                nltk.download(resource, quiet=True)
            except Exception:
                pass


class TextPreprocessor:
    """Clean and normalize text before vectorization"""

    def __init__(self):
        download_nltk_data()
        try:
            self.stop_words = set(stopwords.words('english'))
            self.lemmatizer = WordNetLemmatizer()
            self._use_nltk = True
        except Exception:
            self.stop_words = set()
            self._use_nltk = False

    def clean(self, text):
        """Full preprocessing pipeline"""
        if not isinstance(text, str):
            text = str(text)

        # Lowercase
        text = text.lower()

        # Remove URLs
        text = re.sub(r'http\S+|www\S+', ' URL ', text)

        # Remove HTML tags
        text = re.sub(r'<[^>]+>', ' ', text)

        # Remove special characters (keep alphanumeric and spaces)
        text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)

        # Collapse whitespace
        text = re.sub(r'\s+', ' ', text).strip()

        if self._use_nltk:
            # Tokenize and lemmatize
            tokens = text.split()
            tokens = [
                self.lemmatizer.lemmatize(tok)
                for tok in tokens
                if tok not in self.stop_words and len(tok) > 2
            ]
            text = ' '.join(tokens)

        return text

    def __call__(self, text):
        return self.clean(text)


class DeepfakeTextDetector:
    """
    TF-IDF + Multinomial Naive Bayes pipeline for AI text detection.
    Detects whether text was likely generated by an AI (e.g. GPT, BERT-gen)
    vs. written by a human.
    """

    def __init__(self):
        self.preprocessor = TextPreprocessor()
        self.pipeline = self._build_pipeline()
        self._trained = False

    def _build_pipeline(self):
        """Construct sklearn pipeline"""
        return Pipeline([
            ('tfidf', TfidfVectorizer(
                analyzer='word',
                ngram_range=(1, 3),        # Unigrams, bigrams, trigrams
                max_features=50000,
                min_df=2,
                max_df=0.95,
                sublinear_tf=True,
                strip_accents='unicode'
            )),
            ('clf', CalibratedClassifierCV(
                estimator=MultinomialNB(alpha=0.1),
                cv=5,
                method='sigmoid'
            ))
        ])

    def preprocess_texts(self, texts):
        """Preprocess a list of texts"""
        return [self.preprocessor(t) for t in texts]

    def train(self, texts, labels, sample_weights=None):
        """
        Train the classifier.

        Args:
            texts: List of raw text strings
            labels: List of labels (0 = human, 1 = AI-generated)
            sample_weights: Optional per-sample weights
        """
        cleaned = self.preprocess_texts(texts)
        self.pipeline.fit(cleaned, labels, **({'clf__sample_weight': sample_weights} if sample_weights else {}))
        self._trained = True
        logger.info(f"Text model trained on {len(texts)} samples")

    def predict(self, text):
        """
        Predict whether text is AI-generated.

        Args:
            text: Raw text string

        Returns:
            dict with label, confidence, and probability scores
        """
        if not self._trained:
            # Return demo prediction when untrained
            return self._demo_predict(text)

        cleaned = self.preprocessor(text)
        proba = self.pipeline.predict_proba([cleaned])[0]

        label = 'Fake' if proba[1] > 0.5 else 'Real'
        confidence = float(max(proba))

        return {
            'label': label,
            'confidence': round(confidence, 4),
            'real_probability': round(float(proba[0]), 4),
            'fake_probability': round(float(proba[1]), 4)
        }

    def _demo_predict(self, text):
        """
        Heuristic-based demo prediction for when model is not trained.
        Uses basic linguistic features to estimate AI authorship.
        """
        cleaned = self.preprocessor(text)
        words = cleaned.split()
        num_words = len(words)

        if num_words == 0:
            return {'label': 'Unknown', 'confidence': 0.0, 'real_probability': 0.5, 'fake_probability': 0.5}

        # Heuristic features
        # 1. Unique word ratio (AI tends to be more diverse)
        unique_ratio = len(set(words)) / num_words

        # 2. Average word length
        avg_word_len = np.mean([len(w) for w in words])

        # 3. Sentence length variation (human texts vary more)
        sentences = re.split(r'[.!?]+', text)
        sentence_lens = [len(s.split()) for s in sentences if s.strip()]
        len_std = float(np.std(sentence_lens)) if len(sentence_lens) > 1 else 0

        # Score heuristic (higher = more likely AI)
        score = 0.0
        if unique_ratio > 0.7:
            score += 0.2
        if 4.5 < avg_word_len < 7.0:
            score += 0.2
        if len_std < 5:
            score += 0.15
        if num_words > 100:
            score += 0.1

        # Clamp to plausible range
        score = max(0.1, min(0.9, 0.4 + score))

        label = 'Fake' if score > 0.5 else 'Real'
        confidence = max(score, 1 - score)

        return {
            'label': label,
            'confidence': round(confidence, 4),
            'real_probability': round(1.0 - score, 4),
            'fake_probability': round(score, 4)
        }

    def save(self, path):
        """Save the trained model"""
        joblib.dump({'pipeline': self.pipeline, 'trained': self._trained}, path)
        logger.info(f"Text model saved to {path}")

    def load(self, path):
        """Load a trained model"""
        data = joblib.load(path)
        self.pipeline = data['pipeline']
        self._trained = data.get('trained', True)
        logger.info(f"Text model loaded from {path}")


def load_text_model(model_path=None):
    """Load or initialize the text detection model"""
    detector = DeepfakeTextDetector()

    if model_path:
        try:
            detector.load(model_path)
        except Exception as e:
            logger.warning(f"Could not load text model from {model_path}: {e}. Using demo mode.")
    else:
        logger.warning("No text model path — using heuristic demo mode")

    return detector
